/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project.pkg2nd.sem.visual.novel;

import Storyline.*;
import Storyline.Load;
import Storyline.SettingsHandler;
import Storyline.Settings_Menu;
import Storyline.Storyline;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.*;
/**
 *
 * @author user
 */
public class Title_Screen extends javax.swing.JFrame {

    //Get's the user's device when running and get it's measure ments to be manipulated and use
    //on what size to calculate to make the window/JFrame fit the user's screen.
    private Image female_lead;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int screenWidth = screenSize.width;
    int screenHeight = screenSize.height;
    int Title_xlocation = (int)(0.55989583 * screenWidth);
    int Title_ylocation = (int)(0.11574 * screenHeight);
    /**
     * Creates new form Title_Screen
     */
    public Title_Screen() {
        initComponents();
        //Dynamic file directory.
        female_lead = new ImageIcon(getClass().getResource("/pkgfinal/project/pkg2nd/sem/visual/novel/Sprite & Assets/Female_Scaling_8-removebg-preview.png")).getImage();
        

    Left_Sprite.addComponentListener(new ComponentAdapter() {
        @Override
        public void componentResized(ComponentEvent e) {
            resizeLeftSprite(Left_Sprite.getWidth(), Left_Sprite.getHeight());
        }
    });

    // Initial resize
    resizeLeftSprite(Left_Sprite.getWidth(), Left_Sprite.getHeight());
}
        private void resizeLeftSprite(int width, int height) {
            if (female_lead != null && width > 0 && height > 0) {
                Image scaledImage = female_lead.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                Left_Sprite.setIcon(new ImageIcon(scaledImage)); 
            }
        }

        /*
    Left_Sprite.addComponentListener(new ComponentAdapter() {
        @Override
        public void componentResized(ComponentEvent e) {
            int width = Left_Sprite.getWidth();
            int height = Left_Sprite.getHeight();

            if (width > 0 && height > 0) {
                Image scaledImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                Left_Sprite.setIcon(new ImageIcon(scaledImage));
            }
        }
    });
        */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_Panel = new BackgroundPanel("src\\pkgfinal\\project\\pkg2nd\\sem\\visual\\novel\\Backgrounds\\Pink Background #1.jpg");
        Title_Label = new javax.swing.JLabel();
        Left_Sprite = new javax.swing.JLabel();
        New_Game_Button = new javax.swing.JButton();
        Load_Button = new javax.swing.JButton();
        Settings_Button = new javax.swing.JButton();
        Credits_Button = new javax.swing.JButton();
        Quit_Game_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        Background_Panel.setBackground(new java.awt.Color(102, 255, 255));
        Background_Panel.setPreferredSize(new Dimension(screenWidth, screenHeight));
        setSize(screenWidth, screenHeight);
        Background_Panel.setLayout(null);
        //Background_Panel.setPreferredSize(screenWidth,screenHeight);

        Title_Label.setForeground(new java.awt.Color(255, 0, 0));
        Title_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/pkg2nd/sem/visual/novel/Sprite & Assets/VN Title downscaled 5.png"))); // NOI18N
        Background_Panel.add(Title_Label);
        Title_Label.setBounds(860, 100, 380, 340);
        Title_Label.setBounds(Title_xlocation, Title_ylocation, 380, 340);

        Left_Sprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/pkg2nd/sem/visual/novel/Sprite & Assets/Female_Scaling_8-removebg-preview.png"))); // NOI18N
        Background_Panel.add(Left_Sprite);
        Left_Sprite.setBounds(160, 306, 447, 559);

        New_Game_Button.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        New_Game_Button.setText("New Game");
        New_Game_Button.setPreferredSize(new java.awt.Dimension(72, 23));
        New_Game_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Game_ButtonActionPerformed(evt);
            }
        });
        Background_Panel.add(New_Game_Button);
        New_Game_Button.setBounds(930, 500, 230, 50);
        New_Game_Button.setBounds(Title_xlocation+70, Title_ylocation+400, 230, 50);

        Load_Button.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Load_Button.setText("Load Game");
        Load_Button.setPreferredSize(new java.awt.Dimension(72, 23));
        Load_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Load_ButtonActionPerformed(evt);
            }
        });
        Background_Panel.add(Load_Button);
        Load_Button.setBounds(930, 560, 230, 50);
        Load_Button.setBounds(Title_xlocation+70, Title_ylocation+460, 230, 50);

        Settings_Button.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Settings_Button.setText("Settings");
        Settings_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Settings_ButtonActionPerformed(evt);
            }
        });
        Background_Panel.add(Settings_Button);
        Settings_Button.setBounds(930, 620, 230, 50);
        Settings_Button.setBounds(Title_xlocation+70, Title_ylocation+520, 230, 50);

        Credits_Button.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Credits_Button.setLabel("Credits");
        Credits_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Credits_ButtonActionPerformed(evt);
            }
        });
        Background_Panel.add(Credits_Button);
        Credits_Button.setBounds(930, 680, 230, 50);
        Credits_Button.setBounds(Title_xlocation+70, Title_ylocation+580, 230, 50);

        Quit_Game_Button.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Quit_Game_Button.setText("Quit Game");
        Quit_Game_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quit_Game_ButtonActionPerformed(evt);
            }
        });
        Background_Panel.add(Quit_Game_Button);
        Quit_Game_Button.setBounds(930, 740, 230, 50);
        Quit_Game_Button.setBounds(Title_xlocation+70, Title_ylocation+640, 230, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class BackgroundPanel extends JPanel {
    private Image backgroundImage;

    public BackgroundPanel(String imagePath) {
        // Load the image
        backgroundImage = new ImageIcon(imagePath).getImage();
        // Optional: scale the panel size to fit image
        this.setPreferredSize(new Dimension(screenWidth, screenHeight));
        this.setLayout(null); // or use your desired layout
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Draw scaled background
        g.drawImage(backgroundImage, 0, 0, 1536, 864, this);
    }
}
    
    private void Credits_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Credits_ButtonActionPerformed
        Credits_Screen credits = new Credits_Screen();
        credits.setVisible(true);
    }//GEN-LAST:event_Credits_ButtonActionPerformed

    private void New_Game_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Game_ButtonActionPerformed
        Storyline story = new Storyline();
        story.setVisible(true);
        this.dispose(); // closes the Title Screen
        // TODO add your handling code here:
    }//GEN-LAST:event_New_Game_ButtonActionPerformed

    private void Quit_Game_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quit_Game_ButtonActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Quit_Game_ButtonActionPerformed

    private void Settings_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Settings_ButtonActionPerformed
        Settings_Menu settings = new Settings_Menu(this);
        settings.setModal(true);
        settings.setVisible(true);
        int message_speed = SettingsHandler.getMessageSpeed();
        // TODO add your handling code here:
    }//GEN-LAST:event_Settings_ButtonActionPerformed

    private void Load_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Load_ButtonActionPerformed
        new Load().setVisible(true);
        this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_Load_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Title_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Title_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Title_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Title_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Title_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Title_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background_Panel;
    private javax.swing.JButton Credits_Button;
    private javax.swing.JLabel Left_Sprite;
    private javax.swing.JButton Load_Button;
    private javax.swing.JButton New_Game_Button;
    private javax.swing.JButton Quit_Game_Button;
    private javax.swing.JButton Settings_Button;
    private javax.swing.JLabel Title_Label;
    // End of variables declaration//GEN-END:variables
}
